db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=my_drupal
    - MYSQL_USER=drupal_user
    - MYSQL_PASSWORD=123456
  volumes:
    - /var/lib/mysql
web:
  image: drupal
  links:
    - db:mysql
  ports:
    - "4444:80"
  volumes:
    - /var/www/html/sites
    - /var/www/private